---
- name: Test RHSCL container images on OpenShift 4.X
  hosts: localhost
  vars:
    testing_dir: "/tmp/rhscl_openshift_dir"
    github_repo: "{{ lookup('env', 'GITHUB_REPO')}}"
  tasks:
    - name: Check temporary directory
      block:
        - name: Remove directory
          file:
            state: absent
            path: "{{ testing_dir }}"
        - name: Create temporary directory
          file:
            state: directory
            path: "{{ testing_dir }}"

    - block:
      - name: Check if KUBECONFIG is defined
        command: echo "$KUBECONFIG"
        register: kube
      - name: check if kubeconfig is set
        assert:
          that:
          - kube.stdout != ""
          msg: "KUBECONFIG is not defined"
        changed_when: false
      ignore_errors: no

    - name: Clone and test upstream container repositories
      include_tasks: ./tasks/clone_scl_repo.yml
      loop:
        - s2i-nodejs-container
        - cakephp-ex
        - s2i-ruby-container
        - s2i-python-container
        - s2i-perl-container
        - httpd-container
        - postgresql-container
        - mysql-container
        - mariadb-container
        - nginx-container
        - django-ex
      when: github_repo == ""

    - name: Clone and test only one upstream container repository
      include_tasks: ./tasks/clone_scl_repo.yml
      loop:
        - "{{ github_repo }}"
      when: (github_repo is defined) and (github_repo != "")
