---
- name: Test RHSCL container images on OpenShift 4.X
  hosts: "{{ hosts | default('localhost') }}"
  vars:
    testing_dir: "/tmp/rhscl_openshift_dir"
    github_repo: "{{ lookup('env', 'GITHUB_REPO')}}"
    xml_file_name: "rhscl-testing-results.xml"
    xml_file: "{{ testing_dir }}/{{ xml_file_name }}"
    xml_testsuite_path: "/testsuite"
    xml_testcase_path: "{{ xml_testsuite_path }}/testcase"
  tasks:
    - name: Check temporary directory and create XML unit file
      block:
        - name: Remove directory
          file:
            state: absent
            path: "{{ testing_dir }}"
        - name: Create temporary directory
          file:
            state: directory
            path: "{{ testing_dir }}"

        - name: Copy results template file
          copy:
            src: ./vars/{{ xml_file_name }}
            dest: "{{ xml_file }}"
    - block:
      - name: Check if KUBECONFIG is defined
        command: echo "$KUBECONFIG"
        register: kube
      - name: check if kubeconfig is set
        assert:
          that:
          - kube.stdout != ""
          msg: "KUBECONFIG is not defined"
        changed_when: false
      ignore_errors: no

    - name: Clone and test upstream container repositories
      include_tasks: ./tasks/verify_in_openshift.yml
      loop:
        - nodejs-ex
        - cakephp-ex
        - s2i-ruby-container
        - s2i-python-container
        - s2i-perl-container
        - httpd-container
        - postgresql-container
        - mysql-container
        - mariadb-container
        - nginx-container
        - django-ex
        - s2i-perl-526-container-rhel8
        - s2i-python-36-container-rhel8
        - s2i-python-38-container-rhel8
        - s2i-ruby-25-container-rhel8
        - s2i-ruby-26-container-rhel8
      when: github_repo == ""

    - name: Clone and test only one upstream container repository
      include_tasks: ./tasks/verify_in_openshift.yml
      loop:
        - "{{ github_repo }}"
      when: (github_repo is defined) and (github_repo != "")
