- name: Clone {{ stuff.scl_url }} repository
  git:
    repo: "https://github.com/sclorg/{{ stuff.scl_url }}.git"
    dest: "{{ scl_dir }}"
    recursive: yes
  changed_when: false

- name: Write test case element
  xml:
    path: "{{ xml_file }}"
    xpath: "{{ xml_testsuite_path }}"
    pretty_print: yes
    add_children:
      - testcase:
          name: "{{ stuff.scl_url }}"
